# Configuration for Alacritty, the GPU enhanced terminal emulator
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.6
blur = true
decorations = "ButtonLess"
padding = { x = 6, y = 10 } 
resize_increments = true

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 14

