# Configuration for Alacritty, the GPU enhanced terminal emulator
import = [
    "~/.config/alacritty/themes/themes/xterm.toml"
]

[window]
opacity = 0.2
blur = true
decorations = "ButtonLess"
padding = { x = 8, y = 8 } 
resize_increments = true

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 14

